package com.xy1m;

import java.util.LinkedList;
import java.util.Queue;
import java.util.Stack;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws ArrayIndexOutOfBoundsException, IllegalArgumentException{
        Queue queue = new LinkedList<>();
        queue.add("");
        queue.peek();
        queue.poll();

        Stack stack=new Stack();
        stack.push("");
        stack.pop();
        stack.peek();


    }
}
