package com.zzp;

import java.util.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    /**
     * TODO
     * unicode vs ascii
     *
     *
     *
     * BitOperation operations
     * Heap
     * PriorityQueue
     * Sort
     * Search
     *
     * @param args
     */
    public static void main(String[] args) {
        /*Integer[] res = new Integer[]{1, 2, 3};
        List<Integer> list = Arrays.asList(res);
        list.forEach(e -> {
            System.out.println(e);
        });
        Integer[] res2 = new Integer[2];
        Arrays.fill(res2, 0);
        System.out.println(res2[0]);
        test:
        for(int i=0;i<5;i++){
            Set set=new HashSet();
            for (int j=0;j<5;j++){
                if(j==1){
                    continue test;
                }
            }
        }
        Collections.sort(list,Comparator.reverseOrder());*/
    }
}
